[{"info": "<p>Satellite view is showing Tallinn (for centurys known as Reval), largest city, main port, and the national capital of  Estonia. The city is located on the northern coast of Estonia, along the Gulf of Finland. Tallin has a population of about 400,000. Spoken language is Estonian. The European Capital of Culture in 2011 is home to the Tallinn University of Technology and the Tallinn University.</p>",
  "lat": 59.11958753380499, 
  "long": 25.169677734375, 
  "title": "Tallinn, Estonia", 
  "color": "green"},
  {"info": "<p>Satellite view showing Paris, the national capital and largest city of  France, situated on the River Seine in northern France. Paris has a city population of about 2.15 million inhabitants, in its metropolitan area there live almost 10 million people. The 'The City of Lights' is one of the great cultural centers of Europe, famous for its lifestyle, arts and fashion.</p>",
   "lat": 48.852291406043825, 
   "long": 2.352447509765625, 
   "title": "Paris, France", 
   "color": "yellow"},
  {"info": "<p>Satellite view is showing Berlin, largest city and the national capital of  Germany, located in northeastern Germany, surrounded by the Federal State of Brandenburg, the city center lies along the river Spree. Berlin is also one of the 16 Federal States of Germany. At the end of World War II, the city was occupied by the Allies and divided into two parts: West Berlin and East Berlin. Between 1961 and 1989, the Berlin Wall separated the two parts, which were reunited in 1990.</p>",
   "lat": 52.52374150329883, 
   "long": 13.412246704101562, 
   "title": "Berlin, Germany", 
   "color": "red"},
  {"info": "<p>Satellite view is showing Vienna, at the Danube river, by far the largest city and national capital of  Austria, located in the northeastern part of the country and is close to Slovakia, Czech Republic and Hungary. Vienna developed from early Celtic and Roman settlements into a Medieval and Baroque city. From 1278 to 1918 it was the seat of the Habsburgs and it was until 1918 one of the two capitals of the Austro-Hungarian Empire (the other was Budapest). The Historic center of Vienna is now a UNESCO World Heritage site. Vienna (in German: Wien) is the economic and political center of the 'Alpenrepublik' (Austria, the alps republic), and has long been a center of the arts, esp. music. Mozart, Beethoven, Haydn, and the Strauss family were among the composers who lived and worked there.</p>",
   "lat": 48.21003212234042, 
   "long": 16.369972229003906, 
   "title": "Vienna (Wien), Austria", 
   "color": "blue"},
  {"info": "<p>Satellite view is showing Madrid, largest city, economical and political center and the national capital of  Spain, The city is located on a high plateau in the center of the country at the Manzanares river. In Madrid's metropolitan area (urban area and suburbs) there live almost 6 million people. </p>",
   "lat": 40.41114339950097, 
   "long": -3.6879730224609375, 
   "title": "Madrid, Spain", 
   "color": "purple"},
  {"info": "<p>Founded in the 11th century, it was known as Christiania (or Kristiania) from 1624 until 1924 in honor of Christian IV of Norway and Denmark (1577–1648). The city is the seat of the country's government. Oslo is Norway’s primary city and its cultural, economic, scientific, and political center, and it is an important center of maritime knowledge in Europe. Oslo is considered to be a global city, it is ranked a 'Beta World City Plus'. </p>",
   "lat": 59.91295532794218, 
   "long": 10.74514389038086, 
   "title": "Oslo, Norway", 
   "color": "orange"}, 
  {"info": "<p>Main attractions in Dakar are the Dakar Grand Mosque (built in 1964), one of the most important religious building in the city. Gorée Island, a destination for people interested in the Atlantic slave trade. IFAN Museum of West African culture, one of the oldest art museums in West Africa, the African Renaissance Monument, a 49 m (160ft) high bronze statue. Other attractions are cliff top walks, beaches, major markets, and Hann Park, home to Senegal Zoo.</p>",
   "lat": 14.68855296094455, 
   "long": -17.359771728515625, 
   "title": "Dakar, Senegal", 
   "color": "orange"},
  {"info": "<p>Athens was a flourishing city-state in ancient Greece, it was an important cultural center in the 5th century bc. Athens was chosen as the capital of a newly independent Greece in 1834.</p>",
   "lat": 37.97153793552019, 
   "long": 23.728065490722656, 
   "title": "Athens, Greece", 
   "color": "blue"},  
  {"info": "<p>According to tradition, the ancient city was founded by Romulus (after whom it is named) in 753 bc on the Palatine Hill; as it grew it spread to the other six hills of Rome. Since 1871 Rome is the capital of a unified Italy.</p>",
   "lat": 41.89001042401827, 
   "long": 12.490425109863281, 
   "title": "Rome (Roma), Italy", 
   "color": "green"}]